
registry_offices_ledger = {"Calgary",
                           "Charlottetown",
                           "Edmonton",
                           "Fredericton",
                           "Halifax",
                           "Iqaluit",
                           "Montreal",
                           "Ottowa",
                           "Quebec",
                           "Regina",
                           "Saint John",
                           "Saskatoon",
                           "St. John's",
                           "Toronto",
                           "Vancouver",
                           "Whitehorse",
                           "Winnipeg",
                           "Yellowknife"}
province_ledger = {"Alberta",
                   "British Columbia",
                   "Manitoba",
                   "New Brunswick",
                   "Newfoundland and Labrador",
                   "Nova Scotia",
                   "Nunavut",
                   "Ontario",
                   "Quebec",
                   "Saskatchewan"}
appeal_types_ledger = {"RPD", "RAD", "H&C", "PRRA", "Deferral", "SP", "TRV"}
